[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2 = { path = "../halo2" }
pil_analyzer = { path = "../pil_analyzer" }
number = { path = "../number" }
strum = { version = "0.24.1", features = ["derive"] }
ast = { version = "0.1.0", path = "../ast" }
